spring:
  application:
    name: user
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/user-db}
      auto-index-creation: true

server:
  port: 8081

ttarena:
  jwt:
    secret: ${TTARENA_JWT_SECRET:E0D1A0FDE7DECE0CF1FB3212E468DCCAA9B8707334E6CD50F0DEB47FE679FFF3}
