spring:
  application:
    name: auth

server:
  port: 8080

ttarena:
  jwt:
    secret: ${TTARENA_JWT_SECRET:E0D1A0FDE7DECE0CF1FB3212E468DCCAA9B8707334E6CD50F0DEB47FE679FFF3}

user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://localhost:8081}
