spring:
  application:
    name: auth

server:
  port: 8080

ttarena:
  jwt:
    private-key: ${TTARENA_JWT_PRIVATE_KEY:classpath:keys/dev-private.pem}
    public-key: ${TTARENA_JWT_PUBLIC_KEY:classpath:keys/dev-public.pem}

user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://localhost:8081}
