spring:
  application:
    name: character
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/character-db}
      auto-index-creation: true

server:
  port: ${SERVER_PORT:8083}
  shutdown: graceful

ttarena:
  jwt:
    public-key: ${TTARENA_JWT_PUBLIC_KEY:classpath:keys/dev-public.pem}

character:
  roster:
    max-size: 10
